(function(lib_name,crystal_args,namespace,ua){window.onerror=function(msg,url,line){return false;};if(typeof window[lib_name]!='undefined'){return;}
window[lib_name]=window.crystal2=window.AD2=namespace;eval(namespace.output(lib_name));namespace.crystal_args=crystal_args;var
refs=namespace.__images=[],sendPing=function(url,norandom){var img=new Image(1,1);if(!norandom){var constr='?';if(url.indexOf("?")!=-1){constr='&';}
url=url+constr+Math.random();}
img.src=url;refs.push(img);return this;},report_ua=(function(){for(var i in ua){if(ua[i]!=0){return i+ua[i];}}})(),importScript=namespace.importScript=function(url,callback,charset){var script=document.createElement('script');script.src=url;if(charset){script.charset=charset;}
if(callback){if(ua.ie){script.onreadystatechange=function(){var rs=this.readyState;if("loaded"===rs||"complete"===rs){callback();}};}else{script.onload=callback;}}
document.getElementsByTagName('head')[0].appendChild(script);};try{var channel_match=location.href.match(/(\w+)\.qq\.com/),channel=channel_match&&channel_match[1];}catch(e){var channel;}
var IPingBase={append:doNothing,flush:doNothing,touch:sendPing};if(document.documentElement.contains){namespace.contains=function(a,b){return a!==b&&(a.contains?a.contains(b):true);};}else if(document.documentElement.compareDocumentPosition){namespace.contains=function(a,b){return!!(a.compareDocumentPosition(b)&16);};}else{namespace.contains=function(){return false;};}
var PageSpeedPing=(function(){if(Math.random()>crystal_args.mo_page_ratio){return IPingBase;}
var cutTime=function(num){var s=(num+'');return s.substring(s.length-6);};var stamps={ua:report_ua,domain:channel,QosS:cutTime((function(){if(typeof QosS=='undefined'){return 0;}
if(QosS.G){return QosS.G.startTime||Qoss.G.sT||0;}
if(QosS.Global){return QosS.Global.startTime||0;}
return 0;})())};return mix(instance(IPingBase),{append:function(tag){stamps[tag]=cutTime((new Date()).getTime());},flush:function(){sendPing(crystal_args.mo_page_url+'?'+serializeQuery(stamps));this.flush=function(){};}});})();var fp11input=null;var pageinfo=namespace.pageinfo={'info':null};var limitchar=function(str,maxchar){var cl=str.length;var ret='';var olen=0;for(var i=0;i<cl;i++){var t=encodeURIComponent(str.substr(i,1));olen+=t.length;if(olen<maxchar){ret+=t;}}
return ret;}
var isFromDiscuz=function(fromStr){if(!fromStr){return false;}
return(fromStr.indexOf("/f/discuz")>-1||fromStr.indexOf("search.php?")>-1);}
var collectInfo=function(mode){var info=null;if(namespace.pageinfo['info']!=null){info=namespace.pageinfo['info'];}else{var keywords='',title='',refer='',soso='';each(document.getElementsByTagName("meta"),function(o,i){if(o.getAttribute("name")=="keywords"){keywords=o.getAttribute("content")||'';}});try{title=document.getElementsByTagName("title")[0].innerHTML;refer=document.referrer;var regex=new RegExp("(?:yahoo.+?[\?|&]p=|openfind.+?query=|google.+?q=|lycos.+?query=|onseek.+?keyword=|search\.tom.+?word=|search\.qq\.com.+?word=|zhongsou\.com.+?word=|search\.msn\.com.+?q=|yisou\.com.+?p=|sina.+?word=|sina.+?query=|sina.+?_searchkey=|sohu.+?word=|sohu.+?key_word=|sohu.+?query=|163.+?q=|baidu.+?wd=|baidu.+?kw=|baidu.+?word=|3721\.com.+?p=|Alltheweb.+?q=|soso.+?w=|115.+?q=|youdao.+?q=|sogou.+?query=|bing.+?q=|114.+?kw=|/f/discuz.+q=|/.+/search.php.+?kw=)([^&]*)");var result=refer.match(regex);if(result){var from=result[0];if(result[1].indexOf("%25")===0){result[1]=decodeURIComponent(result[1]);}
if(isFromDiscuz(from)){refer="discuz|"+result[1];}else{try{refer=result[0].substr(0,result[0].indexOf("."))+"|"+result[1];}catch(e){refer=result[0].substr(0,result[0].indexOf("."))+"|"+result[1];}}}else{refer='';}}catch(e){;}
keywords=limitchar(keywords,360);title=limitchar(title,180);refer=refer.substr(0,90);soso=limitchar(soso,90);info={'k':keywords,'t':title,'r':refer,'s':soso};namespace.pageinfo['info']=info;}
if(mode==1){return'&k='+info['k']+'&t='+info['t']+'&r='+info['r']+'&s='+info['s'];}else{return info;}}
var VisitorPingWithHost=(function(){var
pingTemplate="http://{host}/p?oid={oid}&cid={cid}&loc={loc}&aver={aver}&soid={soid}",defaultHost="p.l.asanook.com",cache={},disable=0,createCacheData=function(){return{oid:[],cid:[],loc:[],aver:[],soid:[]};},clearCache=function(){cache={};},clearCacheData=function(host){cache[host]=createCacheData();},flush=function(host,flushData){if(!disable&&flushData.oid.length){flushData.host=host;sendPing(format(pingTemplate,flushData));}},flushAll=function(){each(cache,function(v,k){flush(k,v);});clearCache();};clearCache();return mix(instance(IPingBase),{append:function(data){var host=data.ping||defaultHost;disable=data.disable;if(!cache[host]){cache[host]=createCacheData();}
each(cache[host],function(v,k){v.push(data[k]);});each(cache,function(v,k){var host=k,cacheData=v;if(cacheData.oid.length==5){var cacheDataCopy={};each(cacheData,function(v,k){cacheDataCopy[k]=v.slice(0,15);cacheData[k]=[];});setTimeout(function(){flush(host,cacheDataCopy);},2000);}else{setTimeout(function(){flushAll();},2000);}});},flush:flushAll});})();var VisitorPing=namespace.ping=(function(){var query_strings=['oid','cid','loc','aver','soid'],cache={},clearCache=function(){each(query_strings,function(k){cache[k]=[];});},flush=function(flushdata){var senddata=flushdata?flushdata:cache;if(senddata.oid.length){sendPing(format(crystal_args.ping_template,senddata));if(!flushdata){clearCache();}}},bufferFlush=buffer(flush,2000);clearCache();return mix(instance(IPingBase),{append:function(data){VisitorPingWithHost.append(data);},flush:function(){VisitorPingWithHost.flush();}});})();var getFlashVersion=namespace.getFlashVersion=function(){try{if(typeof window.ActiveXObject!='undefined'){var flash;try{flash=new ActiveXObject('ShockwaveFlash.ShockwaveFlash');}catch(e){for(var i=15;i>5;i--){try{flash=new ActiveXObject('ShockwaveFlash.ShockwaveFlash.'+i);break;}catch(e){}}}
if(!flash){return 0;}
return parseInt(flash.GetVariable("$version").split(" ")[1].split(",")[0],10);}else{return parseInt(navigator.plugins["Shockwave Flash"].description.split(' ')[2],10);}}catch(e){return 0;}};var getFlashObject=namespace.getFlashObject=function(flashId){try{if(window.document[flashId]){return window.document[flashId];}else{return document.getElementById(flashId);}}catch(e){return 0;}};(function(dom,evt,cookie){mix(namespace,{dom:dom,evt:evt,ua:ua,cookie:cookie});evt.on(window,'load',function(){setTimeout(function(){PageSpeedPing.flush();if(crystal_args.mo_ping_script&&Math.random()<crystal_args.mo_ping_ratio){importScript(crystal_args.mo_ping_script);}},1000);});PageSpeedPing.append('js_loaded');evt.ready(function(){if(getFlashVersion()>=11){var flashplayerid=generateId();fp11input=dom.createElement({position:'absolute',left:'-1000px',top:'50px',width:'10px','z-index':-1,cursor:'none'},{type:'text',id:flashplayerid,value:''},'input');var body=document.body||document.documentElement;body.appendChild(fp11input);}
PageSpeedPing.append('page_loaded');});evt.ready(function(){namespace.hackIe7=function(){};var hackIe7Cookie=crystal_args.lview_template.replace('{loc}','_adb_1_10001914')+'&callback=crystal2.hackIe7&rot=1';importScript(hackIe7Cookie);});evt.on(window,'unload',function(){VisitorPing.flush();});namespace.resource=function(file){return crystal_args.file_path+file;};namespace.resource_swf=function(file){return crystal_args.ext_path+file;};var
getExtension=namespace.getExtension=function(uri){try{return/\.(\w+)(?:$|\?)/.exec(uri)[1].toLowerCase();}catch(e){return'jpg';}},htmlEncode=(function(){var el=document.createElement("pre");return function(str){el.innerHTML='';el.appendChild(document.createTextNode(str));return el.innerHTML;};})();namespace.getPlayIndex=function(){return parseInt(cookie.get('ad_play_index'))||Math.floor(Math.random()*100);};var display_index=namespace.getPlayIndex();cookie.set('ad_play_index',display_index+1,{expires:1,path:'/'});var
queue=function(precondition){var preconditioned=false;var precondition_is_running=false;var fns=[];return function(fn){if(preconditioned){fn();}else{fns.push(fn);if(!precondition_is_running){precondition(function(){each(fns,function(f){f();});preconditioned=true;});precondition_is_running=true;}}};},afterImportExtension=queue(function(callback){if(crystal_args.is_debug){crystal_args.extension_js_src+='?_='+(new Date()).getTime();}
importScript(crystal_args.extension_js_src,callback);}),NONE=namespace.NONE=1,IMMEDIATELY=namespace.IMMEDIATELY=2,LAZY=namespace.LAZY=3,default_fodder_count=3,default_index=Math.floor(Math.random()*10)%default_fodder_count,getDefaultFodderUrl=(function(){var scales=[{scale:7.15,size:'960x90'},{scale:2.4,size:'409x114'},{scale:0,size:'300x250'}];var getScale=function(width,height){if(height==0){height=1;}
var s=width/height;for(var i=0;i<scales.length;i++){if(s>=scales[i].scale){return scales[i].size;}}};return function(width,height){return format('http://adsrich.qq.com/web/default_fodders/{scale}_{index}.swf',{scale:getScale(width,height),index:default_index++%default_fodder_count});};})(),getDefaultFodder=function(el){return{resource_url:getDefaultFodderUrl(el.offsetWidth,el.offsetHeight),width:el.offsetWidth,height:el.offsetHeight,cover:false};},dic_display={'banner':{ping:LAZY,render:function(config,el){var fodder=config.fodder[0];if(config.fodder.length==3){var fodder1=config.fodder[1];var fodder2=config.fodder[2];fodder.initvars={'vdo_file':fodder1.resource_url,'vdo_skin':fodder2.resource_url}}
renderFodder(fodder,el,config['icon'],'rb');}},'auto':{ping:IMMEDIATELY,render:function(config,el){renderFodder(getDefaultFodder(el),el);}},'default':{ping:NONE,render:function(config,el){renderFodder(getDefaultFodder(el),el);}},'null':{ping:IMMEDIATELY,render:function(){}},'banner_script_src':{ping:IMMEDIATELY,render:function(config,el){renderFodder(config.fodder[0],el);importScript(config.fodder[1].resource_url);}},'banner_import_monitor_url':{ping:IMMEDIATELY,render:function(config,el){renderFodder(config.fodder[0],el);importScript(config.monitor_url);}},'text':{ping:NONE,render:function(config,el,area_id,ping){if(config.need_ping){ping();}
var fodders=config.fodder;var html=fodders[0];var url=fodders[1];var color=fodders[2];var a=document.createElement('a');a.className=el.className;a.target="_blank";a.href=url;if(color){a.style.color=color;}
a.innerHTML=html;el.parentNode.replaceChild(a,el);if(dom.$(area_id)){arguments.callee(config,dom.$(area_id),area_id,ping);}}},'custom_script':{ping:IMMEDIATELY,render:function(config,el,el_id){var fodder1=config.fodder[0];var scriptUrl=fodder1.resource_url;var splitScriptUrl=scriptUrl.split('.');if(splitScriptUrl.length>0&&splitScriptUrl[splitScriptUrl.length-1]!=='js')
scriptUrl+='.js';document.write('<script id="'+config.cid+'">window.CLICKURL="'+fodder1.link_to+'";</script>');document.write('<script src="'+scriptUrl+'"></script>');}},'overlay':{ping:IMMEDIATELY,render:function(config,el,el_id){if(Object.prototype.toString.call(config.fodder)!=='[object Array]'&&config.fodder.length>1)
return;var htmlFodder=config.fodder[0];var metarialFodder=config.fodder[1];document.write('<script id="'+config.cid+'">window.overlay_click_url="'+htmlFodder.link_to+'";window.overlay_file_url = "'+metarialFodder.resource_url+'";</script>');var scriptUrl=htmlFodder.resource_url;var splitScriptUrl=scriptUrl.split('.');if(splitScriptUrl.length>0&&splitScriptUrl[splitScriptUrl.length-1]!=='js')
scriptUrl+='.js';document.write('<script src="'+scriptUrl+'"></script>');}},'richtext':{ping:IMMEDIATELY,render:function(config,el,area_id,ping){var fodders=config.fodder;var html=fodders[0];var url=fodders[1];var color=fodders[2];var a=document.createElement('a');a.target="_blank";a.href=url;if(color){a.style.color=color;}
a.innerHTML=html;el.parentNode.replaceChild(a,el);dom.setStyle(el,{'height':'12px'});}}},display_buffer={},NO_AD={};var lazyRender;(function(){var event_attached=false,areas={},ping_effect_height=crystal_args.ping_effect_height,pre_load_offset=crystal_args.pre_load_offset,max_used_height=0;var _checkRender=function(force_recalculate){var used_height=dom.getDocumentScrollTop()+dom.getViewportHeight();if(!force_recalculate&&used_height<=max_used_height){return;}
max_used_height=used_height;var rendered_ids=[];each(areas,function(o,id){if(force_recalculate||!o.y){var xy=dom.getXY(o.el);o.y=xy[1];}
if(o.y<=used_height+pre_load_offset){if(!o.rendered){o.render();o.rendered=true;}}
if(o.y<=used_height-ping_effect_height){if(!o.pinged){o.ping();o.pinged=true;}}
if(o.pinged&&o.rendered){rendered_ids.push(id);}});each(rendered_ids,function(id){delete areas[id];});var no_area=true;each(areas,function(){no_area=false;});if(no_area){evt.un(window,'resize',checkRender);evt.un(window,'scroll',checkRender);event_attached=false;}};var checkRender=function(){_checkRender(false);};namespace.forceCheckRender=function(){_checkRender(true);};var bufferCheckRender=buffer(function(){if(!event_attached){checkRender();evt.on(window,'resize',checkRender);evt.on(window,'scroll',checkRender);event_attached=true;}},100);namespace.renderAll=function(){each(areas,function(o,id){if(!o.rendered){o.render();o.rendered=true;}});areas={};evt.un(window,'resize',checkRender);evt.un(window,'scroll',checkRender);event_attached=false;};lazyRender=function(id,render,ping){areas[id]={el:dom.$(id),render:render,rendered:false,ping:ping,pinged:false};bufferCheckRender();};})();var
rendered_area={},in_reqeusting_ids={},renderArea=function(creativity_config,area_id,not_retry){var area=dom.$(area_id);if(!area){if(!not_retry){evt.ready(function(){renderArea(creativity_config,area_id,true);});}
return;}
var render_type=0;area.setAttribute('oid',creativity_config.oid);area.setAttribute('display',creativity_config.display);if(area.getAttribute('immediately')){render_type=IMMEDIATELY;}
var display_handler=namespace.getDisplayHandler(creativity_config.display);if(!display_handler)
return;var pingArea=function(){var posconvert=area_id.indexOf("SLOT");if(posconvert>-1){area_id=area_id.substr(0,posconvert);}
var blackping=['plugin_fullscreen','couplet'];if(indexOf(blackping,creativity_config.display)==-1){VisitorPing.append({loc:area_id,cid:creativity_config.cid||0,oid:creativity_config.oid||0,aver:creativity_config.aver||0,soid:creativity_config.soid||0,ping:creativity_config.ping,disable:creativity_config.ping_disable||0});}
if(creativity_config['monitor_url']){setTimeout(function(){VisitorPing.touch(creativity_config['monitor_url'],true);},1000);}};var render=function(){display_handler.render(creativity_config,area,area_id,pingArea);if(creativity_config.plugins){afterImportExtension(function(){namespace.addPlugins(creativity_config.plugins,creativity_config,area,area_id);});}};var render_type=render_type||display_handler.ping;if(!crystal_args.lazy_render&&render_type==LAZY){render_type=IMMEDIATELY;}
switch(render_type){case IMMEDIATELY:render();pingArea();break;case LAZY:lazyRender(area_id,render,pingArea);break;case NONE:render();break;default:}},buildDefaultCreativityConfig=function(area_id){var el=dom.$(area_id);if(!el||dom.getStyle(el,'display')=='none'){return NO_AD;}
return{display:'auto',oid:89,cid:0};},renderBuffer=function(){each(arguments,function(area_id){if(!rendered_area[area_id]&&!display_buffer[area_id]){display_buffer[area_id]=buildDefaultCreativityConfig(area_id);}});each(display_buffer,function(creativity_config,area_id){if(rendered_area[area_id]){return;}
if(crystal_args.runat!='weibo'){rendered_area[area_id]=true;}
if(creativity_config===NO_AD){return;}
var display=creativity_config.display;if(dic_display[display]){renderArea(creativity_config,area_id);}else{afterImportExtension(function(){renderArea(creativity_config,area_id);});}
delete display_buffer[area_id];});PageSpeedPing.append('start_draw_areas');},isNewArea=function(area_id){if(!rendered_area[area_id]&&!display_buffer[area_id]&&!in_reqeusting_ids[area_id]){in_reqeusting_ids[area_id]=true;return true;}},findAreas=namespace.findAreas=function(){PageSpeedPing.append('search_areas');var areas=map(dom.getElementsByClassName(crystal_args.area_class,crystal_args.element_tags),function(el){return el.id||(el.id=generateId());});PageSpeedPing.append('end_search_areas');return areas;};var rot="&rot=1";var request=namespace.request=function(area0,area1,area2,areaN){var no_data_area_ids;if(area0===true){no_data_area_ids=findAreas();}else{no_data_area_ids=filter(typeof arguments[0]=='string'?arguments:findAreas(),isNewArea);}
if(no_data_area_ids.length){var callback=function(){PageSpeedPing.append('end_request_lview');clearTimeout(timeout_handle);renderBuffer.apply(window,no_data_area_ids);each(no_data_area_ids,function(area_id){delete in_reqeusting_ids[area_id];});};PageSpeedPing.append('request_lview');importScript(format(crystal_args.lview_template,{loc:no_data_area_ids.join(',')})+"&callback="+lib_name+".callbackarea"+rot,callback,crystal_args.charset);rot='';var timeout_handle=setTimeout(callback,crystal_args.lview_time_out*1000);}
renderBuffer();};if(crystal_args.execute_on_ready){evt.ready(request);}
var isArray=function(o){return!!o&&typeof o=='object'&&typeof o.length=='number';};var urlAppendQuery=function(sUrl,dictData,isEncode){return sUrl+(dictData?(sUrl.indexOf('?')==-1?'?':'&')+(serializeDictionary('=','&',false,isEncode))(dictData):'');};var jsonp=function(sUrl,dictData,callback){var methodName=generateId();window[methodName]=function(){callback.apply(null,arguments);setTimeout(function(){try{delete window[methodName];}catch(e){window[methodName]=undefined;}},1);};if(crystal_args.collect){if(crystal_args.runat=='qq'){;}else{}}
importScript(urlAppendQuery(sUrl,mix({'callback':methodName},dictData),false),null,crystal_args.charset);};var getLocData=function(url,locIds,callback){jsonp(url,{loc:locIds.join(',')},callback);};var getLocIds=function(className,tags,callback){callback(map(filter(dom.getElementsByClassName(className,tags),function(el){return!!el.id;}),function(el){return el.id;}));};var requestText=namespace.requestText=function(){getLocIds('w-l-qq-com',['span'],function(arrIds){var arrIds=unique(arrIds);if(arrIds.length==0)
return;var splitIds=[];while(arrIds.length>30){splitIds.push(arrIds.splice(0,30));}
splitIds.push(arrIds.splice(0,arrIds.length));for(var i=0,len=splitIds.length;i<len;i++){(function(){var ids=splitIds[i];getLocData('http://w.l.qq.com/lview?type=text',splitIds[i],function(oLoc){var arrLoc;if(isArray(oLoc)){arrLoc=oLoc;}else{arrLoc=[];each(oLoc,function(config,locId){arrLoc.push(config);});}
each(arrLoc,function(locOrders,i){var locId=ids[i];each(locOrders,function(orderConfig){orderConfig.loc=locId;});});each(arrLoc,function(locOrders){each(locOrders,function(order){renderArea(order,order.loc);});});});})();}});};evt.ready(requestText);var evalcode=namespace.evalcode=function(code){if(window.execScript){window.execScript(code);}else{var fn=function(){window.eval.call(window,code);};fn();}};var DISCUZ_MAX_SLOT_COUNT=crystal_args.MAX_SLOT_COUNT;var renderedSlotsCount=0;var renderedSlots={};var createPlaceHolder=function(slotId,width,height,type){var scripts=document.getElementsByTagName('script');var script=scripts[scripts.length-1],container=dom.createElement({width:width+'px',height:height+'px',overflow:'hidden'});if(slotId=='_adb_14_10002051')container.style.margin=0;if(type||crystal_args.runat!='discuz'){container.id=slotId;}else{container.id=slotId+"SLOT"+generateId();}
script.parentNode.replaceChild(container,script);return container;};var addStaticSlot=function(options){var lview_loaded=false;if(isArray(options)&&options.length){if((typeof options[0]).toLowerCase()=='string'){evalcode(options[0]);return;}else{lview_loaded=true;}}else{return;}
var slotType=options['type']||'';if(!slotType){if(++renderedSlotsCount>DISCUZ_MAX_SLOT_COUNT){return;}}
if(lview_loaded){var slotId=options[0]['loc'];var slotWidth=0;var slotHeight=0;}else{var slotId=options['id'];var slotWidth=options['width']||0;var slotHeight=options['height']||0;}
var slotContainer=createPlaceHolder(slotId,slotWidth,slotHeight,slotType);var real_location_id=slotContainer.id;function render_ad(arrLoc){if(!arrLoc||!arrLoc.length){return;}
var display=arrLoc[0]['display'];if(indexOf(['turner','focusimage'],display)!=-1){arrLoc={display:display,data:arrLoc};renderedSlots[real_location_id]=true;afterImportExtension(function(){renderArea(arrLoc,real_location_id);});}
else if(indexOf(['lightbox'],display)!=-1){var orderConfig=(function(arrConfig){var i=0,minExp=Number.MAX_VALUE,pRecord=-1,pEmptyRecord=-1,time_span=0,cookie_name,isExist=0;for(i=0;i<arrConfig.length;i++){var config=arrConfig[i];var freq_enable=config.display_config.freq_enable||0;time_span=config.display_config.time_span||10;var display_count=config.display_config.display_count||2;var creativeFodder=config.fodder[0];if(creativeFodder.interval){time_span=parseInt(creativeFodder.interval)*60;}
if(creativeFodder.times){display_count=parseInt(creativeFodder.times);}
if(config.oid=='1'){pEmptyRecord=i;continue;}
var timeCookie='_OID_'+config.oid+'_'+config.cid,countCookie=timeCookie+'_C';var since=cookie.get(timeCookie);isExist=0;if(since){if((new Date()).getTime()-since>time_span*1000){cookie.remove(countCookie);cookie.remove(timeCookie);since=(new Date()).getTime();isExist=0;}
else
isExist=cookie.get(countCookie)||0;}else
since=(new Date()).getTime();if(!freq_enable||((new Date()).getTime()-since<time_span*1000&&isExist<display_count)){if(minExp>isExist){minExp=isExist;pRecord=i;}}}
if(pRecord==-1)
pRecord=pEmptyRecord;if(pRecord!=-1){config=arrConfig[pRecord];cookie_name='_OID_'+config.oid+'_'+config.cid;var since=cookie.get(cookie_name);var creativeFodder=config.fodder[0];if(creativeFodder.interval){time_span=parseInt(creativeFodder.interval)*60;}
if(!since||(new Date()).getTime()-since>time_span*1000){cookie.set(cookie_name,(new Date()).getTime(),{expires:1,path:'/',domain:''});}
cookie_name=cookie_name+'_C';minExp++;cookie.set(cookie_name,minExp,{expires:1,path:'/',domain:''});return config;}
return null;})(arrLoc);if(!orderConfig)
return;orderConfig=spec_oid(orderConfig);orderConfig.loc=real_location_id;renderedSlots[real_location_id]=true;var display=orderConfig.display;if(dic_display[display]){renderArea(orderConfig,orderConfig.loc);}else{afterImportExtension(function(){renderArea(orderConfig,orderConfig.loc);});}}else{each(arrLoc,function(locOrders){if(!isArray(locOrders)){locOrders=[locOrders];}
each(locOrders,function(orderConfig){orderConfig=spec_oid(orderConfig);orderConfig.loc=real_location_id;renderedSlots[real_location_id]=true;var display=orderConfig.display;if(dic_display[display]){renderArea(orderConfig,orderConfig.loc);}else{afterImportExtension(function(){renderArea(orderConfig,orderConfig.loc);});}});});}}
if(lview_loaded){render_ad(options);}else{getLocData(crystal_args.lview_template.replace('loc={loc}',''),[slotId],render_ad);}};namespace.addStaticSlot=addStaticSlot;namespace.analyze=function(src){afterImportExtension(function(){importScript(src);});};namespace.render=function(){};var spec_oid=function(cc){if(cc.oid==1){cc['display']='null';}else if(cc.oid==100){cc['display']='auto';}
return cc;}
namespace.area=function(area_config){if(!area_config){return;}
var area_id=area_config.id;display_buffer[area_id]=NO_AD;return function(){if(arguments.length==0){return;}
var creativity_config=arguments[display_index%arguments.length];if(creativity_config.oid==1){creativity_config['display']='null';}
if(creativity_config.oid==100){creativity_config['display']='auto';}
var display=creativity_config['display'];if(indexOf(['turner','focusimage'],display)!=-1){creativity_config={display:display,data:arguments};}
display_buffer[area_id]=creativity_config;};};namespace.callbackarea=function(arrLoc){for(var i=0,len=arrLoc.length;i<len;i++){if(isArray(arrLoc[i])){var func=namespace.area({"id":arrLoc[i][0]['loc']});func.apply(null,arrLoc[i]);}else{var func=namespace.area({"id":arrLoc[i]['loc']});func.apply(null,[arrLoc[i]]);}}}
namespace.getDisplayHandler=function(id){return dic_display[id];};namespace.setDisplayHandler=function(o){mix(dic_display,o);};var ime=namespace.ime={_isAbleInput:true,_isChangeCursor:true,_target:"",_swf:[],_element:fp11input,_setTxt:function(v){this._element.value=v;},setFocus:function(b,swfid,target,txt,index,index1){this._isAbleInput=b;this._target=target;var pos=dom.getXY(dom.$(swfid));dom.setStyle(this._element,{left:pos[0]+'px',top:pos[1]+'px',cursor:'none'});this._element.setAttribute("swfid",swfid);this._element.focus();this._element.blur();this._element.select();if(b){this._isChangeCursor=false;this._setTxt(txt);this._isChangeCursor=true;this.setCaretPosition(this._element,index,index1);}else{this._setTxt("");}},immediately:function(swfid){var element=this._element=fp11input;var lib=this;if(ua.ie){evt.on(element,"propertychange",function(evt){if(evt.propertyName=='value'){lib.webChange(lib,swfid);}});}else{evt.on(element,"input",function(evt){lib.webChange(lib,swfid);},true);}
this.listenKey(lib,swfid);},webChange:function(lib,swfid){if(lib._isAbleInput&&lib._isChangeCursor){lib.outPut(lib,swfid);};},outPut:function(lib,swfid){var targetswf=namespace.getFlashObject(swfid);var activeId=lib._element.getAttribute("swfid");if(lib._target&&swfid==activeId){if(targetswf.getInput){setTimeout(function(){targetswf.getInput(lib._element.value,lib._target,lib.getCursortPosition(lib._element));},100);}}},getCursortPosition:function(ctrl){var CaretPos=0,startPos=0;if(document.selection){ctrl.focus();var Sel=document.selection.createRange(),selLen=Sel.text.length;Sel.moveStart('character',-ctrl.value.length);CaretPos=Sel.text.length;startPos=CaretPos-selLen;}
else if(ctrl.selectionStart||ctrl.selectionStart=='0'){startPos=ctrl.selectionStart;CaretPos=ctrl.selectionEnd;}
return([startPos,CaretPos]);},setCaretPosition:function(ctrl,pos,pos1){if(ctrl.setSelectionRange){ctrl.focus();ctrl.setSelectionRange(pos,pos1);}else if(ctrl.createTextRange){var range=ctrl.createTextRange();range.collapse(true);range.moveEnd('character',pos1);range.moveStart('character',pos);range.select();}},listenKey:function(lib,swfid){if(document.addEventListener){document.addEventListener("keydown",function(event){lib.getKey(event,lib,swfid)},true);}else if(document.attachEvent){document.attachEvent("onkeydown",function(event){lib.getKey(event,lib,swfid)});}else{document.onkeydown=function(event){lib.getKey(event,lib,swfid)};}},getKey:function(e,lib,swfid){e=e||window.event;var keycode=e.which?e.which:e.keyCode;if(keycode==35||keycode==36||keycode==37||keycode==39||keycode==8||keycode==46){lib.outPut(lib,swfid);}}};var DelayClass=Class.create({init:function(){this.invokes=[];},invoke:function(method,args){this.invokes.push(arguments);},set:function(o){this.invoke=function(method,args){return o[method].apply(o,args||[]);};each(this.invokes,function(args){this.invoke(args[0],args[1]);},this);}});(function(){var areas={};namespace.getArea=function(id){return areas[id]||(areas[id]=new DelayClass());};namespace.setArea=function(id,o){namespace.getArea(id).set(o);};})();var renderFodder=namespace.renderFodder=function(fodder,el,icon,iconpos){if(!el){return;}
if(fodder.width){dom.setStyle(el,{display:'block',width:fodder.width,height:fodder.height})}
var temprenderer=renderer[getExtension(fodder.resource_url)];if(temprenderer)
temprenderer(fodder,el);if(dom.getStyle(el,'position')=='static'){el.style.position='relative';}
if(fodder.cover&&fodder.resource_url.indexOf('.gif')<0&&fodder.resource_url.indexOf('.jpg')<0){el.appendChild(createCover(fodder.width,fodder.height,fodder.link_to));}
if(icon&&iconpos){el.appendChild(createIcon(icon,iconpos,fodder.width,fodder.height));}};var createIcon=namespace.createIcon=function(icon,pos,width,height){var m={};var resurl=link_to='';if(pos=='rb'){m={right:0,bottom:0};}else if(pos=='lb'){m={left:0,bottom:0};}
if(icon=='adwin'){resurl=namespace.resource_swf('adwin_'+pos+'.png');m=mix(m,{'width':'55px','height':'20px'});link_to='http://winwfile.qq.com/adwin/jump/jump.htm';}else{m=mix(m,{'width':0,'height':0});}
if(ua.ie==6){m['filter']=format('progid:DXImageTransform.Microsoft.AlphaImageLoader(src=\'{uri}\')',resurl);}else{m['background-image']=format('url({uri})',resurl);}
var style=mix({position:'absolute','z-index':11},m);var icon=dom.createElement(style,{'class':'absolute a_cover',href:htmlEncode(link_to),target:'_blank'},'a');return icon;}
var createCover=namespace.createCover=function(width,height,link_to,left,top){var cover=dom.createElement({position:'absolute',width:width+'px',height:height+'px',left:left||'0px',top:top||'0px',cursor:'pointer','z-index':crystal_args.base_zindex,'background-color':'#fff',filter:'alpha(opacity=0)',opacity:0},{'class':'absolute a_cover',href:htmlEncode(link_to),target:'_blank'},'a');return cover;};var renderer=(function(){var param_template='<param name="{name}" value="{value}"></param>',buildParams=function(o){return map(o,function(v,k){return format(param_template,{name:k,value:v});}).join('');},removeFlash=function(flash){if(!flash||!flash.parentNode){return;}
if(ua.ie){for(var i in flash){if(typeof flash[i]=="function"){flash[i]=null;}}}
flash.parentNode.removeChild(flash);},buildHTML=dom.buildHTML,_renderImage=function(styles,link,el){el.innerHTML=buildHTML(styles,{href:htmlEncode(link),target:'_blank'},'a');return el.firstChild;},renderImage=function(config,el){var styles={display:'block',cursor:'pointer',width:config.width+'px',height:config.height+'px','background-image':format('url({uri})',config.resource_url)};var a=dom.createElement({border:0},{href:config.link_to,target:'_new'},'a');a.innerHTML="<img src='"+config.resource_url+"' width='"+config.width+"' height='"+config.height+"' alt='Click me!' border='0'/>";el.parentNode.appendChild(a);el.style.width=0;el.style.height=0;el.style.margin=0;return a;el.innerHTML="<a href='"+config.link_to+"' target='_new'><img src='"+config.resource_url+"' width='"+config.width+"' height='"+config.height+"' alt='Click me!' border='0'/></a>";return el.firstChild;return _renderImage(styles,config.link_to,el);},renderIEPNG=function(config,el){var styles={display:'block',cursor:'pointer',width:config.width+'px',height:config.height+'px',filter:format('progid:DXImageTransform.Microsoft.AlphaImageLoader(src=\'{uri}\')',config.resource_url)};return _renderImage(styles,config.link_to,el);},renderFlash=function(config,el){var params={allowscriptaccess:'always',wmode:'opaque',quality:'high'};if(config.params){mix(params,config.params);}
var initvars=config.initvars||{};if(config.link_to){initvars['clickTag']=config.link_to;initvars['clicktag']=config.link_to;}
if(getFlashVersion()>=11){initvars['ime']=true;}
if(initvars['ime']){initvars['setFocus']=lib_name+'.ime.setFocus'}
var attrs={id:generateId()};initvars['swfid']=attrs['id'];params.flashvars=serializeQuery(initvars);if(ua.ie){attrs.classid='clsid:D27CDB6E-AE6D-11cf-96B8-444553540000';params.movie=config.resource_url;}else{params.type='application/x-shockwave-flash';attrs.data=config.resource_url;}
el.innerHTML=buildHTML({outline:'none',width:config.width+'px',height:config.height+'px'},attrs,'object',buildParams(params));var flash=el.firstChild;evt.on(window,'unload',function(){removeFlash(flash);});return flash;},renderSl=function(config,el){var params=mix({source:config.resource_url,windowless:true},config.params);var initvars=mix({adlink:config.link_to},config.initvars);params.initParams=serializeQuery(initvars);el.innerHTML=buildHTML({width:config.width+'px',height:config.height+'px'},{type:'application/x-silverlight',data:'data:application/x-silverlight,'},'object',buildParams(params));return el.firstChild;};renderHtml=function(config,el){return el;};return{jpg:renderImage,png:ua.ie==6?renderIEPNG:renderImage,gif:renderImage,swf:renderFlash,xap:renderSl,html:renderHtml};})();})((function(){var el_template='<{tag} {attrs}style="{styles}">{inner}</{tag}>',propertyCache={},patterns={HYPHEN:/(-[a-z])/i,ROOT_TAG:/^body|html$/i},toCamel=function(property){if(!patterns.HYPHEN.test(property)){return property}
if(propertyCache[property]){return propertyCache[property]}
var converted=property;while(patterns.HYPHEN.exec(converted)){converted=converted.replace(RegExp.$1,RegExp.$1.substr(1).toUpperCase())}
propertyCache[property]=converted;return converted},setStyle=(function(){var px=/left|top|right|bottom|width|height/;var transVal=function(k,v){if(px.test(k)&&typeof v=='number'){v=v+'px';}
return v;};if(ua.ie){return function(el,property,val){property=toCamel(property);switch(property){case'opacity':el.style.filter='alpha(opacity='+val*100+')';if(!el.currentStyle||!el.currentStyle.hasLayout){el.style.zoom=1}
break;case'float':property='styleFloat';default:el.style[property]=transVal(property,val);}}}else{return function(el,property,val){property=toCamel(property);if(property=='float'){property='cssFloat'}
el.style[property]=transVal(property,val);}}})(),buildHTML=function(styles,attrs,tag,inner){return format(el_template,{tag:tag||'div',attrs:serializeAttrs(attrs||{}),styles:serializeStyles(styles),inner:inner||''});},getStyle=(function(){if(document.defaultView&&document.defaultView.getComputedStyle){return function(el,property){var value=null;if(property=='float'){property='cssFloat'}
var computed=document.defaultView.getComputedStyle(el,'');if(computed){value=computed[toCamel(property)]}
return el.style[property]||value}}else if(document.documentElement.currentStyle&&ua.ie){return function(el,property){property=toCamel(property);switch(property){case'opacity':var val=100;try{val=el.filters['DXImageTransform.Microsoft.Alpha'].opacity}catch(e){try{val=el.filters('alpha').opacity}catch(e){}}
return val/100;case'float':property='styleFloat';default:var value=el.currentStyle?el.currentStyle[property]:null;return(el.style[property]||value)}}}else{return function(el,property){return el.style[property]}}})(),hasClass=function(elem,className){return elem&&indexOf((elem.className||elem).toString().split(/\s+/),className)>-1;};return{hasClass:hasClass,$:function(id){if(typeof id=='string'){return document.getElementById(id);}
return id;},getStyle:getStyle,setStyle:function(el,k,v){el=el;if(typeof k=='object'){each(k,function(_v,_k){setStyle(el,_k,_v);});}else{setStyle(el,k,v);}},setBackgroundImage:function(el,url){if(ua.ie==6&&/png$/.test(url)){el.style.filter='progid:DXImageTransform.Microsoft.AlphaImageLoader(src=\''+url+'\')';}else{el.style.backgroundImage='url('+url+')';}},buildHTML:buildHTML,createElement:function(html){if(typeof html!='string'){html=buildHTML.apply(window,arguments);}
var el=document.createElement('div');el.innerHTML=html;return el.firstChild;},getElementsByClassName:function(cls,tags){if(document.getElementsByClassName){return document.getElementsByClassName(cls);}
var els=[];each(tags,function(tag){els=filter(document.getElementsByTagName(tag),function(div){return hasClass(div,cls);}).concat(els);});return els;},getXY:function(el){var pos=[el.offsetLeft,el.offsetTop];var parentNode=el.offsetParent;var accountForBody=(ua.webkit&&getStyle(el,'position')=='absolute'&&el.offsetParent==el.ownerDocument.body);if(parentNode!=el){while(parentNode){pos[0]+=parentNode.offsetLeft;pos[1]+=parentNode.offsetTop;if(!accountForBody&&ua.webkit&&getStyle(parentNode,'position')=='absolute'){accountForBody=true}
parentNode=parentNode.offsetParent}}
if(accountForBody){pos[0]-=el.ownerDocument.body.offsetLeft;pos[1]-=el.ownerDocument.body.offsetTop}
parentNode=el.parentNode;while(parentNode.tagName&&!patterns.ROOT_TAG.test(parentNode.tagName)){if(getStyle(parentNode,'display').search(/^inline|table-row.*$/i)){pos[0]-=parentNode.scrollLeft;pos[1]-=parentNode.scrollTop}
parentNode=parentNode.parentNode}
return pos},getDocumentScrollLeft:function(doc){doc=doc||document;return Math.max(doc.documentElement.scrollLeft,doc.body.scrollLeft)},getDocumentScrollTop:function(doc){doc=doc||document;return Math.max(doc.documentElement.scrollTop,doc.body.scrollTop)},getDocumentHeight:function(){var scrollHeight=(document.compatMode!='CSS1Compat')?document.body.scrollHeight:document.documentElement.scrollHeight;var h=Math.max(scrollHeight,this.getViewportHeight());return h},getDocumentWidth:function(){var scrollWidth=(document.compatMode!='CSS1Compat')?document.body.scrollWidth:document.documentElement.scrollWidth;var w=Math.max(scrollWidth,this.getViewportWidth());return w},getViewportHeight:function(){var height=self.innerHeight;var mode=document.compatMode;if((mode||ua.ie)&&!ua.opera){height=(mode=='CSS1Compat')?document.documentElement.clientHeight:document.body.clientHeight}
return height},getViewportWidth:function(){var width=self.innerWidth;var mode=document.compatMode;if(mode||ua.ie){width=(mode=='CSS1Compat')?document.documentElement.clientWidth:document.body.clientWidth}
return width}};})(),(function(){var doc=document.documentElement;var body=document.body;var evt={getPageX:function(e){return('pageX'in e)?e.pageX:e.clientX+(doc&&doc.scrollLeft||body&&body.scrollLeft||0)-(doc&&doc.clientLeft||body&&body.clientLeft||0);},getPageY:function(e){return('pageY'in e)?e.pageY:e.clientY+(doc&&doc.scrollTop||body&&body.scrollTop||0)-(doc&&doc.clientTop||body&&body.clientTop||0);}};if(document.addEventListener){evt.on=function(el,type,handler){el.addEventListener(type,handler,false);return handler;};evt.on2=evt.on;evt.un=function(el,type,handler){el.removeEventListener(type,handler,false);};evt.stopPropagation=function(e){e.stopPropagation();};evt.preventDefault=function(e){e.preventDefault();};evt.getTarget=function(e){return e.target;};evt.getRelTarget=function(e){return e.relatedTarget;};}else{evt.on=function(el,type,handler){el.attachEvent('on'+type,handler);};evt.on2=function(el,type,handler){var actualHandler=function(){handler.call(el,window.event);};el.attachEvent('on'+type,actualHandler);return actualHandler;};evt.un=function(el,type,handler){el.detachEvent('on'+type,handler);};evt.stopPropagation=function(e){e.cancelBubble=true;};evt.preventDefault=function(e){e.returnValue=false;};evt.getTarget=function(e){return e.srcElement;};evt.getRelTarget=function(e){return e.fromElement===e.srcElement?e.toElement:e.fromElement;};}
evt.stop=function(e){evt.stopPropagation(e);evt.preventDefault(e);};(function(){var fns=[];var is_ready=false;evt.ready=function(f){fns.push(f);};var _ready=function(){if(!is_ready){is_ready=true;evt.ready=function(f){f();};each(fns,function(f){f();});}};if(ua.ie){var timer=setInterval(function(){try{document.documentElement.doScroll("left");clearInterval(timer);timer=null;_ready();}catch(ex){}},64);document.attachEvent("onreadystatechange",function(){if(document.readyState==="complete"){document.detachEvent("onreadystatechange",arguments.callee);_ready();}});}else{evt.on(document,"DOMContentLoaded",_ready);}
evt.on(window,'load',_ready);})();return evt;})(),{set:function(key,value,options){var text=key+'='+value;if(options){if(options.expires){text+="; expires="+(new Date((new Date()).getTime()+86400000*options.expires)).toGMTString();}
if(options.path){text+="; path="+options.path;}
if(options.domain){text+="; domain="+options.domain;}
if(options.secure===true){text+="; secure";}}
document.cookie=text;},get:function(key){var o=deserializeString('=','; ',false,false)(document.cookie);return key?o[key]:o;},remove:function(k,options){options=options||{};options.expires=-1;this.set(k,"",options);}});})('crystal',(function(){var crystal_args={area_class:'l_qq_com',element_tags:['div'],execute_on_ready:true,file_path:'http://adsrich.qq.com/web/',ext_path:'http://adsfile.qq.com/web/',is_debug:false,lazy_render:false,lview_template:'http://l.qq.com/lview?c=www&loc={loc}',lview_time_out:6,ping_template:'http://p.l.qq.com/p?oid={oid}&cid={cid}&loc={loc}&aver={aver}&soid={soid}',charset:'gbk',ping_effect_height:-99999,pre_load_offset:100,runat:"adblock",collect:true,mo_page_ratio:0,mo_page_url:'http://dp3.qq.com/web/',mo_ping_ratio:0,mo_ping_script:'',base_zindex:10};crystal_args.extension_js_src=crystal_args.file_path+'crystal/lastest/crystal_ext-min.js';if(crystal_args.runat=='adblock'){crystal_args.lview_template='http://lb.l.asanook.com/lview?loc={loc}';crystal_args.MAX_SLOT_COUNT=999;crystal_args.charset='utf-8';crystal_args.ping_template='http://p.l.asanook.com/p?oid={oid}&cid={cid}&loc={loc}&aver={aver}&soid={soid}';crystal_args.extension_js_src='http://broker.l1.asanook.com/res1/crystal_ext.js';crystal_args.file_path='http://broker.l1.asanook.com/res1/crystal/';crystal_args.ext_path='http://broker.l1.asanook.com/res1/crystal/';}else if(crystal_args.runat=='discuz'){crystal_args.lview_template='http://l2.l.qq.com/lview';crystal_args.MAX_SLOT_COUNT=3;crystal_args.charset='utf-8';crystal_args.ping_template='http://p.l.qq.com/p?oid={oid}&cid={cid}&loc={loc}&aver={aver}&soid={soid}';}else if(crystal_args.runat=='weibo'){crystal_args.lview_template='http://ls.l.qq.com/lview?c=www&loc={loc}';crystal_args.MAX_SLOT_COUNT=999;crystal_args.charset='utf-8';crystal_args.ping_template='http://p.l.qq.com/p?oid={oid}&cid={cid}&loc={loc}&aver={aver}&soid={soid}';crystal_args.extension_js_src=crystal_args.file_path+'crystal/{SNSVERSION}/crystal_ext-min.js';}
if(crystal_args.runat=='qq'){var script=document.getElementById('l_qq_com');try{var input_args=eval('('+script.getAttribute('arguments')+')');for(var i in input_args){crystal_args[i]=input_args[i];}}catch(e){}}
return crystal_args;})(),(function(){var
slice=Array.slice||(function(){var _slice=Array.prototype.slice;return function(arr){return _slice.apply(arr,_slice.call(arguments,1))}})(),mix=function(r){if(!r){r={};}
for(var i=1;i<arguments.length;i++){var s=arguments[i];if(s){for(var j in s){r[j]=s[j];}}}
return r;},each=function(o,fn,context){if(typeof o.length=='number'){for(var i=0,len=o.length;i<len;i++){fn.call(context,o[i],i);}}else if(typeof o=='number'){for(var i=0;i<o;i++){fn.call(context,i,i);}}else{for(var i in o){if(o.hasOwnProperty(i)){fn.call(context,o[i],i);}}}},serializeDictionary=function(assign_token,pair_separator,need_last,need_encode){var encode=need_encode?encodeURIComponent:function(k){return k;};return function(o){var ret=[];each(o,function(v,k){if(k!=null&&v!=undefined){ret.push(encode(k)+assign_token+encode(v));}});return ret.join(pair_separator)+(need_last?pair_separator:'');};},deserializeString=function(assign_token,pair_separator,need_last,need_decode){var decode=need_decode?decodeURIComponent:function(k){return k;};return function(s){var ret={};if(need_last){s=s.replace(new RegExp(pair_separator+'$'),'');}
each(s.split(pair_separator),function(pair){var key_value=pair.split(assign_token);ret[decode(key_value[0])]=decode(key_value[1]);});return ret;};},Class={create:function(proto,sp){var ctor=function(){if(this.init){this.init.apply(this,arguments)}};var mixins_begin_index=1;if(sp&&typeof sp=='function'){var F=function(){};ctor.superclass=F.prototype=sp.prototype;ctor.prototype=new F();mixins_begin_index=2;}
var mixins=slice(arguments,mixins_begin_index);mixins.unshift(proto);mix(ctor.prototype,mix.apply(window,mixins));return ctor}};return{slice:slice,generateId:(function(){var id=1;return function(){return'auto_gen_'+id++}})(),each:each,map:function(o,fn){var ret=[];each(o,function(v,k){ret.push(fn(v,k));});return ret;},unique:function(arr){var len=arr.length;var o={},ret=[];each(arr,function(v,k){o[v]=v;});for(var p in o){if(p!=o[p])
continue;ret.push(p);}
return ret;},filter:function(o,fn){var ret=[];each(o,function(v,k){if(fn(v,k)===true){ret.push(v);}});return ret;},indexOf:function(arr,o){if(arr.indexOf){return arr.indexOf(o);}
for(var i=0;i<arr.length;i++){if(arr[i]===o){return i;}}
return-1;},mix:mix,serializeDictionary:serializeDictionary,deserializeString:deserializeString,serializeStyles:serializeDictionary(':',';',true,false),serializeAttrs:(function(){var fn=serializeDictionary('=',' ',true,false);return function(o){each(o,function(v,k){o[k]='"'+v+'"';});return fn(o);};})(),serializeQuery:serializeDictionary('=','&',false,true),buffer:function(runner,delay){var timer;return function(){if(timer){clearTimeout(timer)}
var args=arguments;timer=setTimeout(function(){runner.apply(window,args)},delay||100);}},format:function(s,config,reserve){return s.replace(/\{([^}]*)\}/g,(typeof config=='object')?function(m,i){var ret=config[i];return ret==null&&reserve?m:ret;}:config);},instance:function(o){var ctor=function(){};ctor.prototype=o;return new ctor();},doNothing:function(){},output:function(lib_name,lib){var eval_arr=[];lib_name=lib_name||'crystal';for(var p in(lib||this)){eval_arr.push('var ');eval_arr.push(p);eval_arr.push('=');eval_arr.push(lib_name);eval_arr.push('.');eval_arr.push(p);eval_arr.push(';');}
return eval_arr.join('');},Class:Class}})(),(function(){var o={ie:0,opera:0,gecko:0,webkit:0,mobile:null};var ua=navigator.userAgent,m;if((/KHTML/).test(ua)){o.webkit=1}
m=ua.match(/AppleWebKit\/([^\s]*)/);if(m&&m[1]){o.webkit=parseFloat(m[1]);if(/ Mobile\//.test(ua)){o.mobile="Apple"}else{m=ua.match(/NokiaN[^\/]*/);if(m){o.mobile=m[0]}}}
if(!o.webkit){m=ua.match(/Opera[\s\/]([^\s]*)/);if(m&&m[1]){o.opera=parseFloat(m[1]);m=ua.match(/Opera Mini[^;]*/);if(m){o.mobile=m[0]}}else{m=ua.match(/MSIE\s([^;]*)/);if(m&&m[1]){o.ie=parseFloat(m[1])}else{m=ua.match(/Gecko\/([^\s]*)/);if(m){o.gecko=1;m=ua.match(/rv:([^\s\)]*)/);if(m&&m[1]){o.gecko=parseFloat(m[1])}}}}}
return o})());var mutex_lock,mutex_unlock;(function(namespace){var locked=false;namespace.mutex_lock=function(){if(locked){return-1;}else{locked=true;return 0;}};namespace.mutex_unlock=function(){locked=false;return 0;};namespace.crystal2_writeSpace=function(loc,testFlag){var timestamp=+new Date();document.write("<script src='http://lb.l.asanook.com/lview?loc="+loc+"&callback=crystal2.addStaticSlot&t="+timestamp+"'><\/script>");return;if(loc=='_adb_14_10000398'){document.write('<script src="http://nf1.asanook.com/jserver/SITE=SABUY.COM/AREA=TEST.AREA/POSITION=POS.CENTER/AAMSZ=125X125/"></script>');return;document.write("<script src='http://lb.l.asanook.com/lview?loc=_adb_14_10002051&callback=crystal2.addStaticSlot&t="+timestamp+"'><\/script>");return;document.writeln('<a href="http://cb.l.asanook.com/lclick?seq=3013032100000005&loc=_adb_14_10000398" target="_new"><img src="http://broker.l1.asanook.com/res1/2013/03/21/67/6746b68941ea40eb.gif" width="125" height="125" alt="Click me!" border="0"></a><img src="http://p.l.asanook.com/p?oid=500001893&cid=200002885&loc=_adb_14_10000398&aver=0" width="1" height="1" style="display:none;"><img src="http://adbroker.asanook.com/ping/test?oid=500001893&cid=200002885&loc=_adb_14_10000398&aver=0" width="1" height="1" style="display:none;">');return;}
document.write("<script src='http://lb.l.asanook.com/lview?loc="+loc+"&callback=crystal2.addStaticSlot&t="+timestamp+"'><\/script>");};})(window);
